# Generated by Django 3.1.4 on 2020-12-22 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('artist', models.ManyToManyField(related_name='records', to='records.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='RecordLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('wikipedia', 'Wikipedia'), ('spotify', 'Spotify')], max_length=200)),
                ('url', models.URLField()),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='records.record')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArtistLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('wikipedia', 'Wikipedia'), ('spotify', 'Spotify')], max_length=200)),
                ('url', models.URLField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='records.artist')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
